name: Despliegue en AWS

on:
  push:
    branches:
      - master2

jobs:
  despliegue-EC2:
    name: Desplegar en ec2
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código del repositorio
      - name: Checkout del código
        uses: actions/checkout@v3

      # 2. Configurar la clave SSH para la conexión con la instancia
      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      # 3. Instalar dependencias en la instancia EC2
      - name: Configurar Python y dependencias
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
            sudo apt update && sudo apt upgrade -y && \
            sudo apt install -y python3 python3-venv python3-pip git
          "

      # 4. Clonar o actualizar el repositorio en la instancia EC2
      - name: Clonar o actualizar el repositorio
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
            if [ ! -d /home/${{ secrets.EC2_USER }}/app ]; then
              git clone https://github.com/GustavoAuger/prueba3 /home/${{ secrets.EC2_USER }}/app;
            else
              cd /home/${{ secrets.EC2_USER }}/app && git pull;
            fi
          "

      # 5. Crear entorno virtual e instalar dependencias
      - name: Crear entorno virtual e instalar dependencias
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
            cd /home/${{ secrets.EC2_USER }}/app/api && \
            python3 -m venv venv && \
            source venv/bin/activate && \
            python3 -m pip install --upgrade pip && \
            python3 -m pip install --no-cache-dir -r requirements.txt --break-system-packages
          "

      # 6. Reiniciar la aplicación
      - name: Verificar existencia de app.py
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
            ls /home/${{ secrets.EC2_USER }}/app/api/app.py
          "

      - name: Reiniciar la aplicación
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
            cd /home/${{ secrets.EC2_USER }}/app/api && \
            source venv/bin/activate && \
            nohup python3 app.py > app.log 2>&1 &
          "

      # 7. Validar el despliegue
    #  - name: Validar el despliegue
  #      run: |
   #       sleep 10
   #       curl -f http://${{ secrets.EC2_IP }}:5000/listar_tareas || exit 1

  ecr-push:
    name: Cargar imagen a ECR
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout del código
        uses: actions/checkout@v4

      # Paso 2: Configurar credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Paso 3: Configurar Docker Buildx
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Paso 4: Cachear capas de Docker para acelerar builds futuros
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-latest
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Paso 5: Iniciar sesión en Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Paso 6: Construir imagen Docker
      - name: Construir imagen Docker
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}:latest .

      # Paso 7: Subir imagen a Amazon ECR
      - name: Subir imagen a Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}:latest
